version: "2"

services:
  #データボリュームコンテナの設計
  db-container:
    image: busybox
    volumes:
      - db-volume:/var/lib/mysql

  #MySQLの設計
  mysql-container:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=dbpass01
    volumes:
      - ./ini:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes_from:
      - db-container
    depends_on:
      - db-container
    restart: always

  #phpmyadminの設計
  pma-container:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql-container
      - PMA_USER=root
      - PMA_PASSWORD=dbpass01
    ports:
      - 8080:80
    depends_on:
      - mysql-container
    restart: always

  #WordPressの設計
  wp-container:
    image: wordpress
    environment:
      - WORDPRESS_DB_HOST=mysql-container
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=dbpass01
    ports:
      - 80:80
    depends_on:
      - mysql-container
    restart: always

  #Redmineの設計
  rm-container:
    image: redmine
    environment:
      - REDMINE_DB_MYSQL=mysql-container
      - REDMINE_DB_USERNAME=root
      - REDMINE_DB_PASSWORD=dbpass01
    ports:
      - 3000:3000
    depends_on:
      - mysql-container
    restart: always

#データボリュームの設計
volumes:
  db-volume: